export const SOURCE_LANGUAGES = [
    { code: 'DT', name: 'Detect language' },
    { code: 'AR', name: 'Arabic' },
    { code: 'BG', name: 'Bulgarian' },
    { code: 'CS', name: 'Czech' },
    { code: 'DA', name: 'Danish' },
    { code: 'DE', name: 'German' },
    { code: 'EL', name: 'Greek' },
    { code: 'EN', name: 'English' }, // All variants
    { code: 'ES', name: 'Spanish' },
    { code: 'ET', name: 'Estonian' },
    { code: 'FI', name: 'Finnish' },
    { code: 'FR', name: 'French' },
    // { code: 'HE', name: 'Hebrew' }, // Pro v2 only
    { code: 'HU', name: 'Hungarian' },
    { code: 'ID', name: 'Indonesian' },
    { code: 'IT', name: 'Italian' },
    { code: 'JA', name: 'Japanese' },
    { code: 'KO', name: 'Korean' },
    { code: 'LT', name: 'Lithuanian' },
    { code: 'LV', name: 'Latvian' },
    { code: 'NB', name: 'Norwegian Bokmål' },
    { code: 'NL', name: 'Dutch' },
    { code: 'PL', name: 'Polish' },
    { code: 'PT', name: 'Portuguese' }, // All variants
    { code: 'RO', name: 'Romanian' },
    { code: 'RU', name: 'Russian' },
    { code: 'SK', name: 'Slovak' },
    { code: 'SL', name: 'Slovenian' },
    { code: 'SV', name: 'Swedish' },
    // { code: 'TH', name: 'Thai' }, // Pro v2 only
    { code: 'TR', name: 'Turkish' },
    { code: 'UK', name: 'Ukrainian' },
    // { code: 'VI', name: 'Vietnamese' }, // Pro v2 only
    // { code: 'ZH', name: 'Chinese' }, // All variants
];

export const TARGET_LANGUAGES = [
    { code: 'AR', name: 'Arabic' },
    { code: 'BG', name: 'Bulgarian' },
    { code: 'CS', name: 'Czech' },
    { code: 'DA', name: 'Danish' },
    { code: 'DE', name: 'German' },
    { code: 'EL', name: 'Greek' },
    { code: 'EN', name: 'English' },
    { code: 'EN-GB', name: 'English (British)' },
    { code: 'EN-US', name: 'English (American)' },
    { code: 'ES', name: 'Spanish' },
    { code: 'ET', name: 'Estonian' },
    { code: 'FI', name: 'Finnish' },
    { code: 'FR', name: 'French' },
    { code: 'HE', name: 'Hebrew (Pro v2 only)' },
    { code: 'HU', name: 'Hungarian' },
    { code: 'ID', name: 'Indonesian' },
    { code: 'IT', name: 'Italian' },
    { code: 'JA', name: 'Japanese' },
    { code: 'KO', name: 'Korean' },
    { code: 'LT', name: 'Lithuanian' },
    { code: 'LV', name: 'Latvian' },
    { code: 'NB', name: 'Norwegian Bokmål' },
    { code: 'NL', name: 'Dutch' },
    { code: 'PL', name: 'Polish' },
    { code: 'PT', name: 'Portuguese' },
    { code: 'PT-BR', name: 'Portuguese (Brazilian)' },
    { code: 'PT-PT', name: 'Portuguese (European)' },
    { code: 'RO', name: 'Romanian' },
    { code: 'RU', name: 'Russian' },
    { code: 'SK', name: 'Slovak' },
    { code: 'SL', name: 'Slovenian' },
    { code: 'SV', name: 'Swedish' },
    // { code: 'TH', name: 'Thai (Pro v2 only)' },
    { code: 'TR', name: 'Turkish' },
    { code: 'UK', name: 'Ukrainian' },
    // { code: 'VI', name: 'Vietnamese (Pro v2 only)' },
    { code: 'ZH', name: 'Chinese' },
    { code: 'ZH-HANS', name: 'Chinese (Simplified)' },
    { code: 'ZH-HANT', name: 'Chinese (Traditional)' },
];
